# Generated by Django 3.2.5 on 2021-07-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210630_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',), 'verbose_name': 'Актёры и режиссёры', 'verbose_name_plural': 'Актёры и режиссёры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',), 'verbose_name': 'МедиаФайл', 'verbose_name_plural': 'МедиаФайлы'},
        ),
        migrations.AlterModelOptions(
            name='movieshots',
            options={'ordering': ('title',), 'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильма'},
        ),
    ]
